lib/sifu_web/router.ex
defmodule SifuWeb.Router do
  use SifuWeb, :router

  import SifuWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SifuWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SifuWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SifuWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      get "/jobs", SifuWeb.ObanController, :list
      get "/jobs/:id/retry", SifuWeb.ObanController, :retry
      live_dashboard "/dashboard", metrics: SifuWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser


      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SifuWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SifuWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/workflow/new/:flow_type",  ProcessController, :new
    post "/workflow/new/:flow_type", ProcessController, :create

    get "/process/:process_id", ProcessController, :show
    
    get "/task/:task_id/user_action", TaskController, :prepare_user_action
    post "/task/:task_id/user_action", TaskController, :process_user_action

    get "/rvat", ProcessController, :list_rvat
    
    get "/users/tasks",    UserTasksController,    :list
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SifuWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/sifu_web/templates/user_tasks/list.html.heex
<div class="fr-container">
    <h1>Mes tâches</h1>
    
    <div class="fr-table">
        <table>
            <thead>
                <tr>
                    <td>#</td>
                    <td>Nom</td>
                    <td>Status</td>
                    <td>Crée le</td>
                    <td>Terminé le</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                <%= for task <- @tasks do %>
                <tr>
                    <td><%= task.id %></td>
                    <td><%= task.flow_node_name %></td>
                    <td><%= task.status %></td>
                    <td><%= if task.started_at != nil, do: Timex.from_now(task.started_at, "fr"), else: "N/D" %></td>
                    <td><%= if task.finished_at != nil, do: Timex.from_now(task.finished_at, "fr"), else: "N/D" %></td>
                    <td><%= link "Executer", to: Routes.task_path(@conn, :prepare_user_action, task.id), class: "fr-btn" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>